config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "prototypes#index"

  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]

     collection do
      get 'popular'
    end
  end

  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show]

end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :like_counts
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  after_create :tag_test

  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :comments
  has_many :tags, through: :prototype_tags
  has_many :prototype_tags, dependent: :destroy
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images
  accepts_nested_attributes_for :tags
  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def tag_test
  end

end

app/models/prototype_tag.rb
class PrototypeTag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag
  validates :prototype_id,presence:true
  validates :tag_id,presence:true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :protypes, through: :prototype_tags
  has_many :prototype_tags, dependent: :destroy
  validates :tags_name,presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments
  has_many :tags

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_prototype

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to "/prototypes/#{@comment.prototype.id}" }
      format.json
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to prototype_path(@prototype), notice: 'Update comment was successfully created'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to "/prototypes/#{@comment.prototype.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(prototype_id: params[:prototype_id], user_id: current_user.id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

   def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(4)
  end

  def popular
    @prototypes = Prototype.order('like_counts DESC').page(params[:page]).per(4)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    @prototype.tags.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    # # @prototype.tags.each_with_index do |tag, index|
    # #   if current_tag = Tag.find_by(tags_name: tag.tags_name)
    # #     @prototype.tags[index].id = current_tag.id
    #     # @prototype.tags = nil
    #   end# @prototype.tags.create()
    # end
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      render :new, alert: 'New prototype was unsuccessfully created'
     end
  end

  def show
    @tag = @prototype.tags
    @comments = @prototype.comments.includes(:user)
    @comment = Comment.new
    @like = Like.find_by(prototype_id: @prototype.id)
  end

  def destroy
    @prototype.destroy
  end

  def edit
    @image = @prototype.captured_images
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to prototype_path, notice: 'Update prototype was successfully created'
    else
      render :edit
     end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status,],
      tags_attributes: [:id, :tags_name]
      )  #.merge(params.require(:tags).permit(:tags_name))
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @prototype = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.row.comments
- if current_user
  .comment-form
    %h4 Comment
    = form_for [@prototype, @comment] do |f|
      = f.text_field :text, {placeholder: "コメントを入力してください", id: "new_comment", class: "textbox"}
      = f.submit "Comment",{class: "button"}

      / %textarea{cols: "100", name: "text", placeholder: "コメントする", rows: "5" , class: "textbox"}
      / %input{type: "submit", value: "SENT"}/

- else
  %h4 Comment
  %textarea{cols: "100", name: "text", placeholder: "コメントする", rows: "5", id: "new_comment"}
  = link_to("/users/sign_in") do
    %input{type: "submit", value: "SENT"}/


.comments-list
  %h4 Comment List
  - if comments
    - comments.each do |comment|
      %p
        %strong
          = comment.user.name
          = comment.text
        -if current_user == comment.user
          = link_to "編集",edit_prototype_comment_path(prototype,comment.id),method: :get, class: "edit-function"
          = link_to '削除',prototype_comment_path(prototype,comment.id),method: :delete, class: "delete-function", remote:true

app/views/comments/destroy.js.erb
$(.comments-list).html("<%= j(render partial: 'comments/comment', locals: {prototype: @prototype, comment: @comment, comments: @comments)} %>")

app/views/comments/edit.html.haml
.proto-page
  .proto-description
    .row.comments
    - if current_user
      .comment-form
        %h4 Edit Your Comment
        = form_for [@prototype, @comment] do |f|
          = f.text_field :text,{class: "edit_comment"}
          = f.submit "Update",{class: "button"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
    = favicon_link_tag('favicon.ico')
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    =button_to prototype_like_path(like, prototype_id: prototype.id), class: "like-decrement", method: :delete, id: "like-button", remote: true do
      = image_tag("icon_red_heart.svg")
      %span.num LIKE #{prototype.like_counts}
  - else
    =button_to prototype_likes_path(prototype), class: "like-increment", id: "like-button", method: :post, remote: true do
      = image_tag("icon_gray_heart.svg")
      %span.num LIKE #{prototype.like_counts}
- else
  %button.like-increment#like-button
    = image_tag("icon_gray_heart.svg")
    %span.num LIKE #{prototype.like_counts}

app/views/likes/create.js.haml
$("#like-buttons").html("#{j(render partial: 'like', locals: { prototype: @prototype, like: @like})}");

app/views/likes/destroy.js.haml
$("#like-buttons").html("#{j(render partial: 'like', locals: { prototype: @prototype, like: @like})}");

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/destroy.html.haml
%h3 削除が完了しました！

=button_to "トップページへ戻る", root_path, method: :get

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = image_tag(@image.main.first.content.large, class: "upload-file-0")
            = f.fields_for :captured_images, @image.main.first do |image|
              = image.file_field :content
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              .image-upload
                -if @image.sub.first
                  = image_tag(@image.sub.first.content, class: "upload-file-1")
                -else
                  %img{class: "upload-file-1"}
                = f.fields_for :captured_images, @image.second do |image|
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload
                -if @image.sub.second
                  = image_tag(@image.sub.second.content, class: "upload-file-2")
                -else
                  %img{class: "upload-file-2"}
                = f.fields_for :captured_images, @image.third do |image|
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload
                -if @image.sub.third
                  = image_tag(@image.sub.third.content, class: "upload-file-3")
                -else
                  %img{class: "upload-file-3"}
                = f.fields_for :captured_images, @image.last do |image|
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          = f.fields_for :tags do |tag|
            = tag.text_field :tags_name
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_prototypes_path, remote:true
        %li.btn-default.btn-newest
          = link_to "Newest", root_path, remote: true
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    =paginate(@prototypes)
    /  デフォルトのpaginationビューを一応残しておきます

    / %li.disabled
    /   %a{"aria-label": "Previous", href: "#"}
    /     %span{"aria-hidden": "true"} «
    / %li.active
    /   %a{href: "#"}
    /     1
    /     %span.sr-only (current)


    / %li
    /   %a{"aria-label": "Next", href: "#"}
    /     %span{"aria-hidden": "true"} »

app/views/prototypes/index.js.erb
$(".container.proto-list").html("<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>")

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img{class: "upload-file-0 "}
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :captured_images do |image|
                  %img{class: "upload-file-1"}
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"

            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :captured_images do |image|
                  %img{class: "upload-file-2"}
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"

            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :captured_images do |image|
                  %img{class: "upload-file-3"}
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, required: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, required: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .col-md-3
            = f.fields_for :tags do |tag|
              = tag.text_field :tags_name, placeholder: "ex) Web"
          .col-md-3
            = f.fields_for :tags do |tag|
              = tag.text_field :tags_name, placeholder: "ex) Rails"
          .col-md-3
            = f.fields_for :tags do |tag|
              = tag.text_field :tags_name, placeholder: "ex) UI/UX"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/popular.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_prototypes_path, remote: true
        %li.btn-default.btn-popular
          = link_to "Newest",root_path, remote: true
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    =paginate(@prototypes)

app/views/prototypes/popular.js.erb
$(".container.proto-list").html("<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>");

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            / view/shared/_headerからコピペしてとって来る？
            = @prototype.title
            - if user_signed_in?
              -if current_user == @prototype.user
                = link_to "編集", edit_prototype_path
                = link_to "削除", prototype_path, method: :delete
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
          .degree
            = @prototype.user.position
    .col-md-6
      #like-buttons
        = render partial:"likes/like", locals: { prototype: @prototype, likes: @likes, like: @like}
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', data: { prototype_id: "#{@prototype.id}" }, style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "tags_path", class: "btn btn-default"}Tag
        %li

          %a{href: "tags_path", class: "btn btn-default"}Tag

        %li
          %a{href: "tags_path", class: "btn btn-default"}Tag

    = render partial: 'comments/comment', locals: {prototype: @prototype, comment: @comment, comments: @comments}

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2018.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_prototypes_path, remote:true
        %li.btn-default.btn-newest
          = link_to "Newest", root_path, remote: true
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"
.container
  .row
    %h2 Tags List
    %ul
      - @tags.each do |tag|
        = link_to "#{tag.tags_name}", tag_path(tag), class: 'btn btn-default'

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_prototypes_path, remote:true
        %li.btn-default.btn-newest
          = link_to "Newest", root_path, remote: true
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container
  = render partial: 'prototypes/prototype', collection: @prototypes

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes